### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [lsunsi/ReduxSwift#4]
`CocoaPods` and `Carthage` are awesome tools and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the _Manual installation_ guide in your `README.md`. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by lsunsi** [comment]
Just updated the README including a manual installation section under "Installation".
I also wrote more detailed Carthage instructions while I was at it. 181d38b638d7cfec6e4b719974b361a9e57b5485
